//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCP
{
    using System;
    using System.Collections.Generic;
    
    public partial class j_customers
    {
        public string id { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string mobile_no { get; set; }
        public string home_no { get; set; }
        public string work_no { get; set; }
        public string alt_no { get; set; }
        public string email { get; set; }
        public string type { get; set; }
        public string reg_number { get; set; }
        public string vat_no { get; set; }
        public string company_name { get; set; }
        public string postal { get; set; }
        public string address_line_1 { get; set; }
        public string address_line_2 { get; set; }
        public string address_line_3 { get; set; }
        public string site_access_id { get; set; }
    }
}
