//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCP
{
    using System;
    using System.Collections.Generic;
    
    public partial class j_job_codes
    {
        public string code { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public int cost { get; set; }
        public int markup { get; set; }
        public int standard_hours { get; set; }
        public int standard_volume { get; set; }
        public int labour_rate { get; set; }
        public string site_access_id { get; set; }
    }
}
