//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCP
{
    using System;
    using System.Collections.Generic;
    
    public partial class j_quote_items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public j_quote_items()
        {
            this.subquotes = new HashSet<j_quote_item_supplier>();
        }
    
        public string id { get; set; }
        public string quote_id { get; set; }
        public int sort_order { get; set; }
        public string job_code { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public int labour_hours { get; set; }
        public int labour_rate { get; set; }
        public int part_rate { get; set; }
        public int part_markup { get; set; }
        public int part_quantity { get; set; }
        public bool auth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<j_quote_item_supplier> subquotes { get; set; }
    }
}
