//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCP
{
    using System;
    using System.Collections.Generic;
    
    public partial class j_quotes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public j_quotes()
        {
            this.items = new HashSet<j_quote_items>();
        }
    
        public string id { get; set; }
        public string ro_number { get; set; }
        public string branch_id { get; set; }
        public string customer_id { get; set; }
        public string vehicle_id { get; set; }
        public string create_user_id { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string update_user_id { get; set; }
        public System.DateTime update_datetime { get; set; }
        public string status { get; set; }
        public int checkin_odometer { get; set; }
        public string tech_id { get; set; }
        public string site_access { get; set; }
    
        public virtual j_customers customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<j_quote_items> items { get; set; }
        public virtual j_users create_user { get; set; }
        public virtual j_techs tech { get; set; }
        public virtual j_users update_user { get; set; }
        public virtual j_vehicles vehicle { get; set; }
    }
}
