//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCP
{
    using System;
    using System.Collections.Generic;
    
    public partial class j_quote_item_supplier
    {
        public string id { get; set; }
        public string supplier_id { get; set; }
        public string quote_item_id { get; set; }
        public int quoted_price { get; set; }
        public string part_number { get; set; }
        public int count { get; set; }
        public string quoted_by { get; set; }
        public System.DateTime quoted_datetime { get; set; }
        public Nullable<System.DateTime> accepted_datetime { get; set; }
        public string accepted_by_user_id { get; set; }
        public string remarks { get; set; }
    
        public virtual j_users user { get; set; }
        public virtual j_supplier_branches supplier { get; set; }
    }
}
