//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCP
{
    using System;
    using System.Collections.Generic;
    
    public partial class j_suppliers
    {
        public string id { get; set; }
        public string name { get; set; }
        public string reg_no { get; set; }
        public string vat_no { get; set; }
        public string tax_clearance { get; set; }
        public Nullable<int> credit_limit { get; set; }
        public Nullable<int> credit_balance { get; set; }
        public string tel_num { get; set; }
        public string contact_person { get; set; }
        public string contact_no { get; set; }
        public string email { get; set; }
        public string after_hours_no { get; set; }
        public string standby_person { get; set; }
        public string standby_no { get; set; }
        public string standby_email { get; set; }
        public string address_line_1 { get; set; }
        public string address_line_2 { get; set; }
        public string address_line_3 { get; set; }
        public string postal { get; set; }
    }
}
