//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCP
{
    using System;
    using System.Collections.Generic;
    
    public partial class j_vehicles
    {
        public string id { get; set; }
        public string customer_id { get; set; }
        public string vin_number { get; set; }
        public string engine_number { get; set; }
        public string registration { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public int year { get; set; }
        public string site_access_id { get; set; }
    }
}
