//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobCostProEntities : DbContext
    {
        public JobCostProEntities()
            : base("name=JobCostProEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<j_customers> j_customers { get; set; }
        public virtual DbSet<j_job_codes> j_job_codes { get; set; }
        public virtual DbSet<j_quote_item_supplier> j_quote_item_supplier { get; set; }
        public virtual DbSet<j_quote_items> j_quote_items { get; set; }
        public virtual DbSet<j_quotes> j_quotes { get; set; }
        public virtual DbSet<j_techs> j_techs { get; set; }
        public virtual DbSet<j_users> j_users { get; set; }
        public virtual DbSet<j_vehicle_models> j_vehicle_models { get; set; }
        public virtual DbSet<j_vehicles> j_vehicles { get; set; }
        public virtual DbSet<j_supplier_branches> j_supplier_branches { get; set; }
        public virtual DbSet<j_suppliers> j_suppliers { get; set; }
        public virtual DbSet<j_errors> j_errors { get; set; }
        public virtual DbSet<j_quote_status> j_quote_status { get; set; }
        public virtual DbSet<j_sites> j_sites { get; set; }
    }
}
