# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: jcpfrontend/package-lock.json
    - name: Build
      run: ./prod.sh && ./staging.sh && ./dev.sh
    - name: Zip Artifact
      run: zip -r publish.zip ./publish
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: publish
        path: publish.zip
    
